#!/usr/bin/env python3
"""generate_twiddle.py -- emit src/twiddle_rom.v, the on-chip zeta table.

Run from anywhere:

    python scripts/generate_twiddle.py

128 entries of 12-bit unsigned, indexed by the twiddle counter k that the
FIPS 203 transforms walk: up from 1 for the forward NTT, down from 127 for the
inverse.

    zeta[k] = 17^brv7(k)  mod q          q = 3329

These are PLAIN zetas -- ordinary field elements in [0, q) -- because this
design reduces with Barrett, and a Barrett butterfly multiplies by zeta
directly. That is the opposite convention from a Montgomery datapath, which
needs the table pre-multiplied by R = 2^16 (the reference Kyber `zetas` array,
beginning -1044, -758, -359, -1517). The two tables are the same size and the
same shape and are completely different numbers, so mixing them up produces a
transform that simulates happily and is wrong by a factor of R at every
butterfly. The self-check below pins down which one this is.

Twelve bits: the largest entry is 3289 < 4096, and every entry is
non-negative, so the whole table is 12-bit unsigned -- the same width as a
coefficient, which is why the ROM output can feed mod_mult with no widening.
"""

import os
import sys

Q = 3329
ZETA = 17
N_TWIDDLE = 128
WIDTH = 12

# The forward transform's first few twiddles, from the FIPS 203 worked example.
REFERENCE_HEAD = [1, 1729, 2580, 3289, 2642, 630, 1897, 848]


def brv7(i):
    """Bit-reverse a 7-bit index -- the order FIPS 203 walks the twiddles in."""
    r = 0
    for b in range(7):
        r = (r << 1) | ((i >> b) & 1)
    return r


def build_table():
    zetas = [pow(ZETA, brv7(i), Q) for i in range(N_TWIDDLE)]

    assert zetas[:8] == REFERENCE_HEAD, f"table head is wrong: {zetas[:8]}"
    assert all(0 <= z < (1 << WIDTH) for z in zetas), "an entry does not fit 12 bits"

    # 17 has order 256 mod q, so the 128 bit-reversed powers are distinct --
    # a duplicate would mean brv7 or the modulus is wrong.
    assert len(set(zetas)) == N_TWIDDLE, "duplicate twiddles"

    # zeta[0] = 1 is never read: both transforms use k in 1..127. It is stored
    # anyway, because leaving a hole in the decode costs a term rather than
    # saving one.
    assert zetas[0] == 1

    return zetas


def emit(zetas):
    out = [
        "// twiddle_rom.v -- GENERATED by scripts/generate_twiddle.py. Do not edit.",
        "//",
        "// The ML-KEM twiddle table, held on chip: zeta[k] = 17^brv7(k) mod q, 128",
        "// entries of 12-bit unsigned. The forward NTT walks k up from 1, the inverse",
        "// walks it down from 127, one step per block -- 127 lookups per transform.",
        "//",
        "// These are PLAIN zetas, ordinary field elements in [0, q). That is the right",
        "// convention for a Barrett datapath, which multiplies by zeta directly. A",
        "// Montgomery datapath would need the table pre-multiplied by R = 2^16 instead",
        "// (the signed reference Kyber `zetas`, -1044, -758, -359, ...). Same width,",
        "// same shape, different numbers.",
        "//",
        "// Combinational, and deliberately so: k changes once per block, and the output",
        "// feeds the first pipeline stage of mod_mult, which has a whole clock to",
        "// settle. Registering the lookup would buy timing nothing needs.",
        "",
        "`default_nettype none",
        "",
        "module twiddle_rom (",
        "    input  wire [6:0]  k,",
        "    output reg  [11:0] zeta",
        ");",
        "",
        "    always @(*) begin",
        "        case (k)",
    ]
    for k, z in enumerate(zetas):
        out.append(f"            7'd{k:<3}: zeta = 12'd{z};")
    out += [
        "            default: zeta = 12'd0;   // unreachable: k is 7 bits, all 128 decoded",
        "        endcase",
        "    end",
        "",
        "endmodule",
        "",
        "`default_nettype wire",
    ]
    return "\n".join(out) + "\n"


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "src", "twiddle_rom.v")
    zetas = build_table()
    with open(path, "w", newline="\n") as f:
        f.write(emit(zetas))
    print(f"wrote {path}: {N_TWIDDLE} entries x {WIDTH} bits, "
          f"range [{min(zetas)}, {max(zetas)}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
