#!/usr/bin/env python3
"""generate_twiddle.py -- emit src/twiddle_rom.v, the on-chip zeta table.

Run from anywhere:

    python scripts/generate_twiddle.py

128 entries of 12-bit SIGNED, indexed by the twiddle counter k that the
FIPS 203 transforms walk: up from 1 for the forward NTT, down from 127 for the
inverse.

    zeta[k] = centre( 17^brv7(k) * R  mod q )        R = 2^16, q = 3329

The table is stored in the MONTGOMERY DOMAIN -- pre-multiplied by R -- for the
reason the textbook gives in Key Idea 6.1:

    "Montgomery does not return a mod q. It returns a*R^-1 mod q -- there is a
     spurious factor R^-1. The fix is to keep everything in the Montgomery
     domain... Our zetas table is stored pre-multiplied by R for exactly this
     reason, so fqmul(zeta*R, x) = zeta*x comes out with no stray factor."

So this table is bit-identical to the reference Kyber `zetas` array, beginning
-1044, -758, -359, -1517. A table of plain zetas (1, 1729, 2580, ...) is what a
Barrett-only datapath would want and is wrong here: it would synthesise and
simulate happily and produce a transform off by a factor of R at every
butterfly. The self-check below pins down which one this is.

Twelve bits: centre() lands every entry in (-q/2, q/2], and 12-bit two's
complement spans -2048..2047, so the signed table needs no more width than an
unsigned one -- the sign bit comes free rather than costing a 13th bit.
"""

import os
import sys

Q = 3329
ZETA = 17
R = 1 << 16
N_TWIDDLE = 128
WIDTH = 12

# The first eight entries of the reference Kyber `zetas` array.
REFERENCE_HEAD = [-1044, -758, -359, -1517, 1493, 1422, 287, 202]


def brv7(i):
    """Bit-reverse a 7-bit index -- the order FIPS 203 walks the twiddles in."""
    r = 0
    for b in range(7):
        r = (r << 1) | ((i >> b) & 1)
    return r


def centre(x):
    """Representative of x in the centred range (-q/2, q/2]."""
    x %= Q
    return x - Q if x > Q // 2 else x


def build_table():
    zetas = [centre(pow(ZETA, brv7(i), Q) * R) for i in range(N_TWIDDLE)]

    assert zetas[:8] == REFERENCE_HEAD, (
        f"table does not match the reference Kyber zetas: {zetas[:8]}")

    lo, hi = -(1 << (WIDTH - 1)), (1 << (WIDTH - 1)) - 1
    for k, z in enumerate(zetas):
        assert lo <= z <= hi, f"zeta[{k}] = {z} does not fit in {WIDTH} bits"

    # 17 has order 256 mod q, so the 128 bit-reversed powers are distinct.
    assert len(set(zetas)) == N_TWIDDLE, "duplicate twiddles"

    # zeta[0] is R mod q centred. Neither transform reads it -- both start at
    # k = 1 -- but it is stored anyway, because leaving a hole in the decode
    # costs a term rather than saving one.
    assert zetas[0] == centre(R % Q)
    return zetas


HEADER = [
    "// twiddle_rom.v -- GENERATED by scripts/generate_twiddle.py. Do not edit.",
    "//",
    "// The ML-KEM twiddle table, held on chip: zeta[k] = centre(17^brv7(k) * R mod q),",
    "// 128 entries of 12-bit signed, bit-identical to the reference Kyber `zetas`",
    "// array. The forward NTT walks k up from 1, the inverse walks it down from 127,",
    "// one step per block -- 127 lookups per transform.",
    "//",
    "// MONTGOMERY DOMAIN: every entry is pre-multiplied by R = 2^16, so that fqmul,",
    "// which returns a*b*R^-1 mod q, gives fqmul(zeta*R, x) = zeta*x with no stray",
    "// factor to undo. That is Key Idea 6.1 of the textbook. The `plain` column in",
    "// each comment is the ordinary zeta^brv7(k) mod q, shown only so the table can",
    "// be checked against a textbook; the hardware never uses it.",
    "//",
    "// Combinational, and deliberately so: k changes once per block, and the output",
    "// feeds the first pipeline stage of fqmul, which has a whole clock to settle.",
    "",
    "`default_nettype none",
    "",
    "module twiddle_rom (",
    "    input  wire [6:0]        k,",
    "    output reg signed [11:0] zeta",
    ");",
    "",
    "    always @(*) begin",
    "        case (k)",
]

FOOTER = [
    "            default: zeta = 12'sd0;   // unreachable: k is 7 bits, all 128 decoded",
    "        endcase",
    "    end",
    "",
    "endmodule",
    "",
    "`default_nettype wire",
]


def emit(zetas):
    plain = [pow(ZETA, brv7(i), Q) for i in range(N_TWIDDLE)]
    out = list(HEADER)
    for k, z in enumerate(zetas):
        lit = f"-12'sd{-z}" if z < 0 else f" 12'sd{z}"
        out.append(f"            7'd{k:<3}: zeta = {lit};  // plain {plain[k]}")
    out += FOOTER
    return "\n".join(out) + "\n"


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "src", "twiddle_rom.v")
    zetas = build_table()
    with open(path, "w", newline="\n") as f:
        f.write(emit(zetas))
    print(f"wrote {path}: {N_TWIDDLE} entries x {WIDTH} bits, "
          f"range [{min(zetas)}, {max(zetas)}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
