"""
generate_twiddle.py -- regenerate src/twiddle_rom.v

The ROM holds zeta^brv7(i) * R mod q, centred and carried as signed 16-bit
values: the twiddle table in Montgomery form. Storing it pre-multiplied by R is
what makes a butterfly multiply come out clean, since
fqmul(zeta*R, x) = zeta*R*x*R^-1 = zeta*x.

The resulting table is bit-identical to the reference Kyber `zetas` array.

    python scripts/generate_twiddle.py > src/twiddle_rom.v
"""

Q = 3329
ZETA = 17
R = 1 << 16


def brv7(i):
    r = 0
    for b in range(7):
        r = (r << 1) | ((i >> b) & 1)
    return r


def centre(x):
    x %= Q
    return x - Q if x > Q // 2 else x


ZETAS = [centre(pow(ZETA, brv7(i), Q) * R) for i in range(128)]

HEADER = """// twiddle_rom.v -- ML-KEM twiddle factors in Montgomery form
//
// zetas[i] = zeta^brv7(i) * R mod q, centred into (-q/2, q/2] and carried as
// a signed 16-bit value. This is bit-identical to the reference Kyber `zetas`
// table, which starts -1044, -758, -359, -1517, ...
//
// Storing the table pre-multiplied by R is what makes the butterfly multiply
// come out clean: fqmul(zeta*R, x) = zeta*R*x*R^-1 = zeta*x, with no stray
// Montgomery factor to correct afterwards.
//
// The forward transform walks k up from 1; the inverse walks it down from 127.
// Index 0 holds R mod q itself and is not used by either transform.
//
// Generated by scripts/generate_twiddle.py -- do not edit by hand.

`default_nettype none

module twiddle_rom (
    input  wire        [6:0] k,
    output reg signed [15:0] zeta
);
    always @(*) begin
        case (k)"""

if __name__ == "__main__":
    assert ZETAS[:4] == [-1044, -758, -359, -1517], ZETAS[:4]
    print(HEADER)
    for i, z in enumerate(ZETAS):
        if z < 0:
            print(f"            7'd{i}: zeta = -16'sd{-z};")
        else:
            print(f"            7'd{i}: zeta =  16'sd{z};")
    print("""            default: zeta = 16'sd0;
        endcase
    end
endmodule

`default_nettype wire""")
