// twiddle_rom.v -- GENERATED by scripts/generate_twiddle.py. Do not edit.
//
// The ML-KEM twiddle table, held on chip: zeta[k] = centre(17^brv7(k) * R mod q),
// 128 entries of 12-bit signed, bit-identical to the reference Kyber `zetas`
// array. The forward NTT walks k up from 1, the inverse walks it down from 127,
// one step per block -- 127 lookups per transform.
//
// MONTGOMERY DOMAIN: every entry is pre-multiplied by R = 2^16, so that fqmul,
// which returns a*b*R^-1 mod q, gives fqmul(zeta*R, x) = zeta*x with no stray
// factor to undo. That is Key Idea 6.1 of the textbook. The `plain` column in
// each comment is the ordinary zeta^brv7(k) mod q, shown only so the table can
// be checked against a textbook; the hardware never uses it.
//
// Combinational, and deliberately so: k changes once per block, and the output
// feeds the first pipeline stage of fqmul, which has a whole clock to settle.

`default_nettype none

module twiddle_rom (
    input  wire [6:0]        k,
    output reg signed [11:0] zeta
);

    always @(*) begin
        case (k)
            7'd0  : zeta = -12'sd1044;  // plain 1
            7'd1  : zeta = -12'sd758;  // plain 1729
            7'd2  : zeta = -12'sd359;  // plain 2580
            7'd3  : zeta = -12'sd1517;  // plain 3289
            7'd4  : zeta =  12'sd1493;  // plain 2642
            7'd5  : zeta =  12'sd1422;  // plain 630
            7'd6  : zeta =  12'sd287;  // plain 1897
            7'd7  : zeta =  12'sd202;  // plain 848
            7'd8  : zeta = -12'sd171;  // plain 1062
            7'd9  : zeta =  12'sd622;  // plain 1919
            7'd10 : zeta =  12'sd1577;  // plain 193
            7'd11 : zeta =  12'sd182;  // plain 797
            7'd12 : zeta =  12'sd962;  // plain 2786
            7'd13 : zeta = -12'sd1202;  // plain 3260
            7'd14 : zeta = -12'sd1474;  // plain 569
            7'd15 : zeta =  12'sd1468;  // plain 1746
            7'd16 : zeta =  12'sd573;  // plain 296
            7'd17 : zeta = -12'sd1325;  // plain 2447
            7'd18 : zeta =  12'sd264;  // plain 1339
            7'd19 : zeta =  12'sd383;  // plain 1476
            7'd20 : zeta = -12'sd829;  // plain 3046
            7'd21 : zeta =  12'sd1458;  // plain 56
            7'd22 : zeta = -12'sd1602;  // plain 2240
            7'd23 : zeta = -12'sd130;  // plain 1333
            7'd24 : zeta = -12'sd681;  // plain 1426
            7'd25 : zeta =  12'sd1017;  // plain 2094
            7'd26 : zeta =  12'sd732;  // plain 535
            7'd27 : zeta =  12'sd608;  // plain 2882
            7'd28 : zeta = -12'sd1542;  // plain 2393
            7'd29 : zeta =  12'sd411;  // plain 2879
            7'd30 : zeta = -12'sd205;  // plain 1974
            7'd31 : zeta = -12'sd1571;  // plain 821
            7'd32 : zeta =  12'sd1223;  // plain 289
            7'd33 : zeta =  12'sd652;  // plain 331
            7'd34 : zeta = -12'sd552;  // plain 3253
            7'd35 : zeta =  12'sd1015;  // plain 1756
            7'd36 : zeta = -12'sd1293;  // plain 1197
            7'd37 : zeta =  12'sd1491;  // plain 2304
            7'd38 : zeta = -12'sd282;  // plain 2277
            7'd39 : zeta = -12'sd1544;  // plain 2055
            7'd40 : zeta =  12'sd516;  // plain 650
            7'd41 : zeta = -12'sd8;  // plain 1977
            7'd42 : zeta = -12'sd320;  // plain 2513
            7'd43 : zeta = -12'sd666;  // plain 632
            7'd44 : zeta = -12'sd1618;  // plain 2865
            7'd45 : zeta = -12'sd1162;  // plain 33
            7'd46 : zeta =  12'sd126;  // plain 1320
            7'd47 : zeta =  12'sd1469;  // plain 1915
            7'd48 : zeta = -12'sd853;  // plain 2319
            7'd49 : zeta = -12'sd90;  // plain 1435
            7'd50 : zeta = -12'sd271;  // plain 807
            7'd51 : zeta =  12'sd830;  // plain 452
            7'd52 : zeta =  12'sd107;  // plain 1438
            7'd53 : zeta = -12'sd1421;  // plain 2868
            7'd54 : zeta = -12'sd247;  // plain 1534
            7'd55 : zeta = -12'sd951;  // plain 2402
            7'd56 : zeta = -12'sd398;  // plain 2647
            7'd57 : zeta =  12'sd961;  // plain 2617
            7'd58 : zeta = -12'sd1508;  // plain 1481
            7'd59 : zeta = -12'sd725;  // plain 648
            7'd60 : zeta =  12'sd448;  // plain 2474
            7'd61 : zeta = -12'sd1065;  // plain 3110
            7'd62 : zeta =  12'sd677;  // plain 1227
            7'd63 : zeta = -12'sd1275;  // plain 910
            7'd64 : zeta = -12'sd1103;  // plain 17
            7'd65 : zeta =  12'sd430;  // plain 2761
            7'd66 : zeta =  12'sd555;  // plain 583
            7'd67 : zeta =  12'sd843;  // plain 2649
            7'd68 : zeta = -12'sd1251;  // plain 1637
            7'd69 : zeta =  12'sd871;  // plain 723
            7'd70 : zeta =  12'sd1550;  // plain 2288
            7'd71 : zeta =  12'sd105;  // plain 1100
            7'd72 : zeta =  12'sd422;  // plain 1409
            7'd73 : zeta =  12'sd587;  // plain 2662
            7'd74 : zeta =  12'sd177;  // plain 3281
            7'd75 : zeta = -12'sd235;  // plain 233
            7'd76 : zeta = -12'sd291;  // plain 756
            7'd77 : zeta = -12'sd460;  // plain 2156
            7'd78 : zeta =  12'sd1574;  // plain 3015
            7'd79 : zeta =  12'sd1653;  // plain 3050
            7'd80 : zeta = -12'sd246;  // plain 1703
            7'd81 : zeta =  12'sd778;  // plain 1651
            7'd82 : zeta =  12'sd1159;  // plain 2789
            7'd83 : zeta = -12'sd147;  // plain 1789
            7'd84 : zeta = -12'sd777;  // plain 1847
            7'd85 : zeta =  12'sd1483;  // plain 952
            7'd86 : zeta = -12'sd602;  // plain 1461
            7'd87 : zeta =  12'sd1119;  // plain 2687
            7'd88 : zeta = -12'sd1590;  // plain 939
            7'd89 : zeta =  12'sd644;  // plain 2308
            7'd90 : zeta = -12'sd872;  // plain 2437
            7'd91 : zeta =  12'sd349;  // plain 2388
            7'd92 : zeta =  12'sd418;  // plain 733
            7'd93 : zeta =  12'sd329;  // plain 2337
            7'd94 : zeta = -12'sd156;  // plain 268
            7'd95 : zeta = -12'sd75;  // plain 641
            7'd96 : zeta =  12'sd817;  // plain 1584
            7'd97 : zeta =  12'sd1097;  // plain 2298
            7'd98 : zeta =  12'sd603;  // plain 2037
            7'd99 : zeta =  12'sd610;  // plain 3220
            7'd100: zeta =  12'sd1322;  // plain 375
            7'd101: zeta = -12'sd1285;  // plain 2549
            7'd102: zeta = -12'sd1465;  // plain 2090
            7'd103: zeta =  12'sd384;  // plain 1645
            7'd104: zeta = -12'sd1215;  // plain 1063
            7'd105: zeta = -12'sd136;  // plain 319
            7'd106: zeta =  12'sd1218;  // plain 2773
            7'd107: zeta = -12'sd1335;  // plain 757
            7'd108: zeta = -12'sd874;  // plain 2099
            7'd109: zeta =  12'sd220;  // plain 561
            7'd110: zeta = -12'sd1187;  // plain 2466
            7'd111: zeta = -12'sd1659;  // plain 2594
            7'd112: zeta = -12'sd1185;  // plain 2804
            7'd113: zeta = -12'sd1530;  // plain 1092
            7'd114: zeta = -12'sd1278;  // plain 403
            7'd115: zeta =  12'sd794;  // plain 1026
            7'd116: zeta = -12'sd1510;  // plain 1143
            7'd117: zeta = -12'sd854;  // plain 2150
            7'd118: zeta = -12'sd870;  // plain 2775
            7'd119: zeta =  12'sd478;  // plain 886
            7'd120: zeta = -12'sd108;  // plain 1722
            7'd121: zeta = -12'sd308;  // plain 1212
            7'd122: zeta =  12'sd996;  // plain 1874
            7'd123: zeta =  12'sd991;  // plain 1029
            7'd124: zeta =  12'sd958;  // plain 2110
            7'd125: zeta = -12'sd1460;  // plain 2935
            7'd126: zeta =  12'sd1522;  // plain 885
            7'd127: zeta =  12'sd1628;  // plain 2154
            default: zeta = 12'sd0;   // unreachable: k is 7 bits, all 128 decoded
        endcase
    end

endmodule

`default_nettype wire
